account:
  long: "&AWS; Account Management"
  short: Account
  sort: Account Management
  version: 2021-02-01
chime-sdk-voice:
  long: "Amazon Chime SDK Voice"
  short: Chime SDK Voice
  sort: Chime SDK Voice
  version: 2022-08-03
datazone:
  long: "Amazon DataZone"
  short: DataZone
  sort: DataZone
  version: 2018-05-10
dms:
  long: "&AWS; Database Migration Service"
  short: DMS
  sort: Database Migration Service
  version: 2016-01-01
kinesisvideo:
  long: "Amazon Kinesis Video Streams"
  short: Kinesis Video
  sort: Kinesis Video Streams
  version: 2017-09-30
mq:
  long: "Amazon MQ"
  short: Amazon MQ
  sort: MQ
  version: 2017-11-27
network-firewall:
  long: "&AWS; Network Firewall"
  short: Network Firewall
  sort: Network Firewall
  version: 2020-11-12
pinpoint-sms-voice-v2:
  long: "&AWS; End User Messaging"
  short: End User Messaging
  sort: End User Messaging
  version: 2022-03-31
qbusiness:
  long: "Amazon Q Business"
  short: Q Business
  sort: Q Business
  version: 2023-11-27
sso-admin:
  long: "&AWS; IAM Identity Center"
  short: IAM Identity Center
  sort: IAM Identity Center
  version: 2020-07-20
